language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t fredrikolsson/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fredrikolsson/udemy-docker-react npm run test